    - run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        # Chỉ add nếu file tồn tại
        [ -f list-kenh.m3u ] && git add list-kenh.m3u
        git commit -m "Update" || exit 0
        git push
        
